version: "3.9"

services:

  backend:
    build: ./Backend
    container_name: lpr_backend
    ports:
      - "8000:8000"
    volumes:
      - ./Backend/temp:/app/temp
      - ./Backend/production_models:/app/production_models
    restart: always

  frontend:
    build:
      context: ./Frontend
      args:  # ✅ must be under build
        NEXT_PUBLIC_BACKEND_URL: http://localhost:8000
        NEXT_PUBLIC_WS_URL: ws://localhost:8000/ws
    container_name: lpr_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always